# Generated by Django 2.2 on 2021-11-23 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=150, verbose_name='注册平台')),
            ],
        ),
        migrations.CreateModel(
            name='Versio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, verbose_name='账户用户名')),
                ('password', models.CharField(max_length=250, verbose_name='账户密码')),
                ('nl_contact_id', models.CharField(max_length=6, verbose_name='nl联系人id')),
                ('be_contact_id', models.CharField(max_length=6, verbose_name='be联系人id')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('register_platform', models.ManyToManyField(to='registerplatform.RegisterPlatform', verbose_name='注册平台')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.Member', verbose_name='Versio归属')),
            ],
            options={
                'verbose_name': 'Versio账户',
                'verbose_name_plural': 'Versio账户',
            },
        ),
        migrations.CreateModel(
            name='Openprovider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, verbose_name='账户用户名')),
                ('password', models.CharField(max_length=250, verbose_name='账户密码')),
                ('nl_contact_id', models.CharField(max_length=20, verbose_name='nl联系人id')),
                ('be_contact_id', models.CharField(max_length=20, verbose_name='be联系人id')),
                ('es_contact_id', models.CharField(max_length=20, verbose_name='es联系人id')),
                ('fr_contact_id', models.CharField(max_length=20, verbose_name='fr联系人id')),
                ('ch_contact_id', models.CharField(max_length=20, verbose_name='ch联系人id')),
                ('de_contact_id', models.CharField(max_length=20, verbose_name='de联系人id')),
                ('eu_contact_id', models.CharField(max_length=20, verbose_name='eu联系人id')),
                ('it_contact_id', models.CharField(max_length=20, verbose_name='it联系人id')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('register_platform', models.ManyToManyField(to='registerplatform.RegisterPlatform', verbose_name='注册平台')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.Member', verbose_name='Openprovider归属')),
            ],
            options={
                'verbose_name': 'Openprovider账户',
                'verbose_name_plural': 'Openprovider账户',
            },
        ),
        migrations.CreateModel(
            name='Godaddy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=250, verbose_name='api_key')),
                ('api_secret', models.CharField(max_length=250, verbose_name='api_secret')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.Member', verbose_name='api归属')),
            ],
            options={
                'verbose_name': 'Godaddy账户',
                'verbose_name_plural': 'Godaddy账户',
            },
        ),
        migrations.CreateModel(
            name='AfterMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=250, verbose_name='api_key')),
                ('api_secret', models.CharField(max_length=250, verbose_name='api_secret')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('register_platform', models.ManyToManyField(to='registerplatform.RegisterPlatform', verbose_name='注册平台')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.Member', verbose_name='api归属')),
            ],
            options={
                'verbose_name': 'AfterMarket账户',
                'verbose_name_plural': 'AfterMarket账户',
            },
        ),
    ]
