# Generated by Django 2.2 on 2021-11-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('domain', '0001_initial'),
        ('registerplatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='register_platform',
            field=models.ManyToManyField(to='registerplatform.RegisterPlatform', verbose_name='注册平台'),
        ),
        migrations.AddField(
            model_name='domain',
            name='user',
            field=models.ManyToManyField(to='member.Member', verbose_name='域名归属'),
        ),
    ]
